version: '3.0'
services:
  frontend:
    image: "gcr.io/pasteblink-222512/pasteblink-frontend:v9"
  # frontend:
  #   image: "mhart/alpine-node:11"
  #   volumes:
  #     - ./:/code
  #   working_dir: "/code"
  #   command: "npm run serve"
  server:
    image: "mhart/alpine-node:11"
    volumes:
      - ../pasteblink:/code
    # environment:
    #   - CLIENT_HANDLER_DEBUG=5
    working_dir: "/code"
    command: "node app"
    ports:
      - "8888:8888"
      - "3000:3000"
  # server:
  #   image: "gcr.io/pasteblink-222512/pasteblink:v16"
  #   ports:
  #     - "8888:8888"
  #     - "3000:3000"
  #   environment:
  #     - frontend_server_address=frontend:8080
  #     - cookie_secret=qwweerrt
